yapiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-node-monitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: redis-node
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

