apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-node
  template:
    metadata:
      labels:
        app: redis-node
    spec:
      containers:
        - name: redis-node
          image: redis-node:v1
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis-master:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis-master:6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-node-service
spec:
  type: NodePort
  selector:
    app: redis-node
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000

