alertmanager:
  enabled: false

server:
  service:
    type: NodePort          # accès web facile
    nodePort: 30090         # http://<IP-minikube>:30090
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { cpu: 300m, memory: 256Mi }

extraScrapeConfigs: |
  - job_name: node-backend
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-node-service.default.svc.cluster.local:80']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter.monitoring.svc.cluster.local:9121']
